services: 
  php:
    build: 
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./website:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./db.ini.php:/var/www/html/config/db.ini.php
  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - 8080:80
    volumes:
      - ./website:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: test123
      MARIADB_USER: fr_http
      MARIADB_USER_PASSWORD: stickan
  phpMyAdmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
